name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v2

    - name: Install deps
      run: pnpm i

    - name: Compile sass
      run: pnpm run sass

    - name: Build
      run: python3 generate_adblock_rules.py

    - name: Store artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rules
        path: |
          adblock.rules.txt
          style.css
        if-no-files-found: error
